language: go
go:
  - 1.17.x

go_import_path: github.com/opklnm102/hello-echo
  
# cache:
#  directories:
#    - ${TRAVIS_BUILD_DIR}/vendor

install:
  - go mod download

script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: echo "not master build ${TRAVIS_COMMIT}"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master
    skip_cleanup: true
  - provider: script
    script: bash build
    on:
      all_branches: true
  - provider: script
    script: echo "master build tagging latest"
    on:
      branch: master
  - provider: script
    script: echo "tag build ${TRAVIS_TAG}"
    on:
      tags: true
